/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.mythicrealms.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.mythicrealms.item.inventory.BackpackItemInventoryCapability;
import net.mcreator.mythicrealms.item.*;
import net.mcreator.mythicrealms.MythicrealmsMod;

import java.util.function.Function;

@EventBusSubscriber
public class MythicrealmsModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(MythicrealmsMod.MODID);
	public static final DeferredItem<Item> TANK_ROLE;
	public static final DeferredItem<Item> GIANT_ROLE;
	public static final DeferredItem<Item> GUARDIAN_ROLE;
	public static final DeferredItem<Item> BARBARIAN_ROLE;
	public static final DeferredItem<Item> ASSASSIN_ROLE;
	public static final DeferredItem<Item> SOLDIER_ROLE;
	public static final DeferredItem<Item> INVESTIGATOR_ROLE;
	public static final DeferredItem<Item> HUNTER_ROLE;
	public static final DeferredItem<Item> MONK_ROLE;
	public static final DeferredItem<Item> WIZARD_ROLE;
	public static final DeferredItem<Item> SUMMONER_ROLE;
	public static final DeferredItem<Item> DRUID_ROLE;
	public static final DeferredItem<Item> STEEL_INGOT;
	public static final DeferredItem<Item> STEEL_PLATE;
	public static final DeferredItem<Item> TITANIUM_INGOT;
	public static final DeferredItem<Item> TITANIUM_ORE;
	public static final DeferredItem<Item> VIBRANIUM_ORE;
	public static final DeferredItem<Item> VIBRANIUM_INGOT;
	public static final DeferredItem<Item> STEEL_PICKAXE;
	public static final DeferredItem<Item> STEEL_AXE;
	public static final DeferredItem<Item> STEEL_SWORD;
	public static final DeferredItem<Item> STEEL_SHOVEL;
	public static final DeferredItem<Item> STEEL_HOE;
	public static final DeferredItem<Item> ADAMANT_ORE;
	public static final DeferredItem<Item> ADAMANT_INGOT;
	public static final DeferredItem<Item> GHOST_HORSE_SPAWN_EGG;
	public static final DeferredItem<Item> NIGHTMARE_HORSE_SPAWN_EGG;
	public static final DeferredItem<Item> HIPPOCAMPUS_SPAWN_EGG;
	public static final DeferredItem<Item> MINERS_DREAM;
	public static final DeferredItem<Item> CAVE_MAGIC_BOOK;
	public static final DeferredItem<Item> DASH_MAGIC_BOOK;
	public static final DeferredItem<Item> EARTHQUAKE_MAGIC_BOOK;
	public static final DeferredItem<Item> FIRE_BALL_MAGIC_BOOK;
	public static final DeferredItem<Item> GHOST_MODE_MAGIC_BOOK;
	public static final DeferredItem<Item> HEAL_MAGIC_BOOK;
	public static final DeferredItem<Item> ICE_BALL_MAGIC_BOOK;
	public static final DeferredItem<Item> LIFE_STEAL_MAGIC_BOOK;
	public static final DeferredItem<Item> METEOR_MAGIC_BOOK;
	public static final DeferredItem<Item> NECROMANCER_MAGIC_BOOK;
	public static final DeferredItem<Item> SAND_STORM_MAGIC_BOOK;
	public static final DeferredItem<Item> SMOKE_MODE_MAGIC_BOOK;
	public static final DeferredItem<Item> SOULFORCE_STEAL_MAGIC_BOOK;
	public static final DeferredItem<Item> STOP_TIME_MAGIC_BOOK;
	public static final DeferredItem<Item> THUNDER_MAGIC_BOOK;
	public static final DeferredItem<Item> HIGHEST_SOUND_MAGIC_BOOK;
	public static final DeferredItem<Item> ACCELARATION_MAGIC_BOOK;
	public static final DeferredItem<Item> EXPELL_MAGIC_BOOK;
	public static final DeferredItem<Item> DETECT_MAGIC_BOOK;
	public static final DeferredItem<Item> VULCAN_MAGIC_BOOK;
	public static final DeferredItem<Item> BLACK_HOLE_MAGIC_BOOK;
	public static final DeferredItem<Item> REFLECT_MAGIC_BOOK;
	public static final DeferredItem<Item> DEEPWORLD_TRAVEL_MACHINE;
	public static final DeferredItem<Item> DEEPWORLD_PORTAL;
	public static final DeferredItem<Item> LUNAR_BLOCK;
	public static final DeferredItem<Item> POISON_CLOUD_MAGIC_BOOK;
	public static final DeferredItem<Item> LIGHT_TRAVEL_MAGIC_BOOK;
	public static final DeferredItem<Item> WATER_BREATH_MAGIC_BOOK;
	public static final DeferredItem<Item> PANDEMIC_SPAWN_EGG;
	public static final DeferredItem<Item> YETI_SPAWN_EGG;
	public static final DeferredItem<Item> JOKER_SPAWN_EGG;
	public static final DeferredItem<Item> VAMPIRE_SPAWN_EGG;
	public static final DeferredItem<Item> BLOOD_LOG;
	public static final DeferredItem<Item> BLOOD_WOOD;
	public static final DeferredItem<Item> STRIPPED_BLOOD_LOG;
	public static final DeferredItem<Item> STRIPPED_BLOOD_WOOD;
	public static final DeferredItem<Item> BLOOD_PLANKS;
	public static final DeferredItem<Item> BLOOD_LEAVES;
	public static final DeferredItem<Item> BLOOD_STAIRS;
	public static final DeferredItem<Item> BLOOD_SLAB;
	public static final DeferredItem<Item> BLOOD_FENCE;
	public static final DeferredItem<Item> BLOOD_FENCE_GATE;
	public static final DeferredItem<Item> BLOOD_DOOR;
	public static final DeferredItem<Item> BLOOD_TRAPDOOR;
	public static final DeferredItem<Item> BLOOD_PRESSURE_PLATE;
	public static final DeferredItem<Item> BLOOD_BUTTON;
	public static final DeferredItem<Item> BLOOD_SAPLING;
	public static final DeferredItem<Item> BLOOD_BOTTLE;
	public static final DeferredItem<Item> BLOOD_INGOT;
	public static final DeferredItem<Item> DRACULA_SPAWN_EGG;
	public static final DeferredItem<Item> BLOOD_POTIONS;
	public static final DeferredItem<Item> LAVA_GOLEM_SPAWN_EGG;
	public static final DeferredItem<Item> BLOOD_ARMOR_HELMET;
	public static final DeferredItem<Item> BLOOD_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> BLOOD_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> BLOOD_ARMOR_BOOTS;
	public static final DeferredItem<Item> NOBLE_STEEL;
	public static final DeferredItem<Item> SAMURAI_ARMOR_HELMET;
	public static final DeferredItem<Item> SAMURAI_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> SAMURAI_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> SAMURAI_ARMOR_BOOTS;
	public static final DeferredItem<Item> GHOST_MUSHROOM;
	public static final DeferredItem<Item> BLOOD_GRASS;
	public static final DeferredItem<Item> MUMMY_SPAWN_EGG;
	public static final DeferredItem<Item> PHARAOH_SPAWN_EGG;
	public static final DeferredItem<Item> ENT_SPAWN_EGG;
	public static final DeferredItem<Item> KITSUNE_SPAWN_EGG;
	public static final DeferredItem<Item> STURGEON_SPAWN_EGG;
	public static final DeferredItem<Item> VENRAID_SPAWN_EGG;
	public static final DeferredItem<Item> VENRAID_SCALE;
	public static final DeferredItem<Item> VENRAID_ARMOR_HELMET;
	public static final DeferredItem<Item> VENRAID_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> VENRAID_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> VENRAID_ARMOR_BOOTS;
	public static final DeferredItem<Item> BANDAGE;
	public static final DeferredItem<Item> PHARAOH_ARMOR_HELMET;
	public static final DeferredItem<Item> PHARAOH_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> PHARAOH_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> PHARAOH_ARMOR_BOOTS;
	public static final DeferredItem<Item> SCARAB_GEM;
	public static final DeferredItem<Item> TECH_ARMOR_HELMET;
	public static final DeferredItem<Item> TECH_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> TECH_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> TECH_ARMOR_BOOTS;
	public static final DeferredItem<Item> NINJA_ARMOR_HELMET;
	public static final DeferredItem<Item> NINJA_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> NINJA_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> NINJA_ARMOR_BOOTS;
	public static final DeferredItem<Item> REINFORCED_LEATHER;
	public static final DeferredItem<Item> ANGEL_FEATHER;
	public static final DeferredItem<Item> ANGEL_INGOT;
	public static final DeferredItem<Item> ANGEL_ARMOR_HELMET;
	public static final DeferredItem<Item> ANGEL_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ANGEL_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ANGEL_ARMOR_BOOTS;
	public static final DeferredItem<Item> DEMON_ARMOR_HELMET;
	public static final DeferredItem<Item> DEMON_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> DEMON_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> DEMON_ARMOR_BOOTS;
	public static final DeferredItem<Item> DEMON_SCALE;
	public static final DeferredItem<Item> DEMON_INGOT;
	public static final DeferredItem<Item> ENT_ARMOR_HELMET;
	public static final DeferredItem<Item> ENT_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ENT_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ENT_ARMOR_BOOTS;
	public static final DeferredItem<Item> MAGIC_SAPLING;
	public static final DeferredItem<Item> MAGIC_LOG;
	public static final DeferredItem<Item> MAGIC_WOOD;
	public static final DeferredItem<Item> STRIPPED_MAGIC_LOG;
	public static final DeferredItem<Item> STRIPPED_MAGIC_WOOD;
	public static final DeferredItem<Item> MAGIC_PLANKS;
	public static final DeferredItem<Item> MAGIC_LEAVES;
	public static final DeferredItem<Item> MAGIC_STAIRS;
	public static final DeferredItem<Item> MAGIC_SLAB;
	public static final DeferredItem<Item> MAGIC_FENCE;
	public static final DeferredItem<Item> MAGIC_FENCE_GATE;
	public static final DeferredItem<Item> MAGIC_DOOR;
	public static final DeferredItem<Item> MAGIC_TRAPDOOR;
	public static final DeferredItem<Item> MAGIC_PRESSURE_PLATE;
	public static final DeferredItem<Item> MAGIC_BUTTON;
	public static final DeferredItem<Item> TEMPEST_MAGIC_BOOK;
	public static final DeferredItem<Item> BARRIER_MAGIC_BOOK;
	public static final DeferredItem<Item> BLOOD_SWORD;
	public static final DeferredItem<Item> BACKPACK_ITEM;
	public static final DeferredItem<Item> SHIELD_OF_ATHENA;
	public static final DeferredItem<Item> BOW_OF_APOLLO;
	public static final DeferredItem<Item> PUMPKIN_STAFF;
	public static final DeferredItem<Item> VENRAID_SWORD;
	public static final DeferredItem<Item> NECRO_BOOK;
	public static final DeferredItem<Item> RELIGION_BOOK;
	public static final DeferredItem<Item> SOULFORCE_BOOK;
	public static final DeferredItem<Item> ILLUMINATY_ITEM;
	public static final DeferredItem<Item> TANMAKU_SWORD;
	public static final DeferredItem<Item> EGYPTIAN_SWORD;
	public static final DeferredItem<Item> TANMAKE;
	public static final DeferredItem<Item> MAGNET;
	public static final DeferredItem<Item> MAGNETIC_ROCK;
	public static final DeferredItem<Item> ANTI_MAGNETIC_ROCK;
	public static final DeferredItem<Item> MAGNET_ARMOR_HELMET;
	public static final DeferredItem<Item> MAGNET_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> MAGNET_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> MAGNET_ARMOR_BOOTS;
	public static final DeferredItem<Item> PALLADIO_BLOCK;
	public static final DeferredItem<Item> PALLADIO_INGOT;
	public static final DeferredItem<Item> RAW_PALLADIO;
	public static final DeferredItem<Item> RAW_ADAMANT;
	public static final DeferredItem<Item> RAW_TITANIUM;
	public static final DeferredItem<Item> RAW_VIBRANIUM;
	public static final DeferredItem<Item> MANA_POTION;
	public static final DeferredItem<Item> MANA_BOTTLE;
	public static final DeferredItem<Item> ANGEL_SPAWN_EGG;
	public static final DeferredItem<Item> DEMON_SPAWN_EGG;
	public static final DeferredItem<Item> YGGDRASIL_LOG;
	public static final DeferredItem<Item> YGGDRASIL_WOOD;
	public static final DeferredItem<Item> STRIPPED_YGGDRASIL_LOG;
	public static final DeferredItem<Item> STRIPPED_YGGDRASIL_WOOD;
	public static final DeferredItem<Item> YGGDRASIL_PLANKS;
	public static final DeferredItem<Item> YGGDRASIL_LEAVES;
	public static final DeferredItem<Item> YGGDRASIL_STAIRS;
	public static final DeferredItem<Item> YGGDRASIL_SLAB;
	public static final DeferredItem<Item> YGGDRASIL_FENCE;
	public static final DeferredItem<Item> YGGDRASIL_FENCE_GATE;
	public static final DeferredItem<Item> YGGDRASIL_DOOR;
	public static final DeferredItem<Item> YGGDRASIL_TRAPDOOR;
	public static final DeferredItem<Item> YGGDRASIL_PRESSURE_PLATE;
	public static final DeferredItem<Item> YGGDRASIL_BUTTON;
	public static final DeferredItem<Item> YGGDRASIL_SAPLING;
	public static final DeferredItem<Item> WENDIGO_SPAWN_EGG;
	public static final DeferredItem<Item> TECH_GOOGLES_ITEM;
	public static final DeferredItem<Item> PALLADIO_ARMOR_HELMET;
	public static final DeferredItem<Item> PALLADIO_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> PALLADIO_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> PALLADIO_ARMOR_BOOTS;
	public static final DeferredItem<Item> URANIUM;
	public static final DeferredItem<Item> URANIUM_BLOCK;
	public static final DeferredItem<Item> ENRICHED_URANIUM;
	public static final DeferredItem<Item> XOCHITL_POWDER;
	public static final DeferredItem<Item> XOCHITL_LEATHER;
	public static final DeferredItem<Item> XOCHITL_INGOT;
	public static final DeferredItem<Item> XOCHITL_SPAWN_EGG;
	public static final DeferredItem<Item> STAR_DUST;
	public static final DeferredItem<Item> SAND_OF_STAR;
	public static final DeferredItem<Item> TOXIC_SAND;
	public static final DeferredItem<Item> MYTHRILL;
	public static final DeferredItem<Item> SKIES_STONE;
	public static final DeferredItem<Item> MYTHRILL_ORE;
	public static final DeferredItem<Item> SKIES_GRASS;
	public static final DeferredItem<Item> SKIES_STONE_BRICKS;
	public static final DeferredItem<Item> TOXIC_SLIME;
	public static final DeferredItem<Item> ULTIMATE_INGOT;
	public static final DeferredItem<Item> NANOS;
	public static final DeferredItem<Item> PEDESTAL;
	public static final DeferredItem<Item> LUNAR_COBBLESTONE;
	public static final DeferredItem<Item> LUNAR_COBBLE_SLAB;
	public static final DeferredItem<Item> NANO_ARMOR_HELMET;
	public static final DeferredItem<Item> NANO_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> NANO_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> NANO_ARMOR_BOOTS;
	public static final DeferredItem<Item> ACTIVED_NANO;
	public static final DeferredItem<Item> CRYSTAL_BARRIER_BLOCK;
	public static final DeferredItem<Item> GLACITE;
	public static final DeferredItem<Item> GLACITE_ORE;
	public static final DeferredItem<Item> FLAMITE_ORE;
	public static final DeferredItem<Item> FLAMITE;
	public static final DeferredItem<Item> NANITE;
	public static final DeferredItem<Item> XOCHITL_ARMOR_HELMET;
	public static final DeferredItem<Item> XOCHITL_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> XOCHITL_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> XOCHITL_ARMOR_BOOTS;
	public static final DeferredItem<Item> WENDIGO_BONE;
	public static final DeferredItem<Item> WENDIGO_ARMOR_ARMOR_HELMET;
	public static final DeferredItem<Item> WENDIGO_ARMOR_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> WENDIGO_ARMOR_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> WENDIGO_ARMOR_ARMOR_BOOTS;
	public static final DeferredItem<Item> ORICALC;
	public static final DeferredItem<Item> MAGIC_ARMOR_HELMET;
	public static final DeferredItem<Item> MAGIC_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> MAGIC_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> MAGIC_ARMOR_BOOTS;
	public static final DeferredItem<Item> MAGIC_ARMOR_MAGIC_BOOK;
	public static final DeferredItem<Item> SUBSTITUTE_MAGIC_BOOK;
	public static final DeferredItem<Item> FIRE_WAVE_MAGIC_BOOK;
	public static final DeferredItem<Item> FLY_MAGIC_BOOK;
	public static final DeferredItem<Item> LANCE;
	public static final DeferredItem<Item> CHIMERA_GUN_ITEM;
	public static final DeferredItem<Item> SPECTATE_MAGIC_BOOK;
	public static final DeferredItem<Item> TECH_JETPACK_ITEM;
	public static final DeferredItem<Item> TOMOE_RING_ITEM;
	public static final DeferredItem<Item> UNICORN_SPAWN_EGG;
	public static final DeferredItem<Item> RING;
	public static final DeferredItem<Item> WATER_STONE;
	public static final DeferredItem<Item> OCEAN_PORTAL;
	public static final DeferredItem<Item> ICE_AGE_MAGIC_BOOK;
	public static final DeferredItem<Item> DESERT_MAGIC_BOOK;
	public static final DeferredItem<Item> FANG;
	public static final DeferredItem<Item> WEREWOLF_FANG;
	public static final DeferredItem<Item> WEREWOLF_ARMOR_HELMET;
	public static final DeferredItem<Item> WEREWOLF_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> WEREWOLF_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> WEREWOLF_ARMOR_BOOTS;
	public static final DeferredItem<Item> BLOOD_CRYSTAL;
	public static final DeferredItem<Item> WEREWOLF_CHESTPLATE_INCOMPLETE;
	public static final DeferredItem<Item> CRYSTAL;
	public static final DeferredItem<Item> CRYSTAL_ORE;
	public static final DeferredItem<Item> SKY_PORTAL;
	public static final DeferredItem<Item> SOLID_BLOOD;
	public static final DeferredItem<Item> BLOOD_BUCKET;
	public static final DeferredItem<Item> CAPACITOR;
	public static final DeferredItem<Item> TESLA_ARMOR_HELMET;
	public static final DeferredItem<Item> TESLA_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> TESLA_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> TESLA_ARMOR_BOOTS;
	public static final DeferredItem<Item> DIVINE_SWORD;
	public static final DeferredItem<Item> MJOLNIR;
	public static final DeferredItem<Item> HAMMER;
	public static final DeferredItem<Item> TANMAKU_HAMMER;
	public static final DeferredItem<Item> KATANA;
	public static final DeferredItem<Item> PRE_HISTORY_ARMOR_HELMET;
	public static final DeferredItem<Item> PRE_HISTORY_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> PRE_HISTORY_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> PRE_HISTORY_ARMOR_BOOTS;
	public static final DeferredItem<Item> SOUL_ITEM;
	public static final DeferredItem<Item> SOULFORCE_POTION;
	public static final DeferredItem<Item> SOUL_INGOT;
	public static final DeferredItem<Item> EGYPTIAN_GOD_ARMOR_HELMET;
	public static final DeferredItem<Item> EGYPTIAN_GOD_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> EGYPTIAN_GOD_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> EGYPTIAN_GOD_ARMOR_BOOTS;
	public static final DeferredItem<Item> DIVINE_INGOT;
	public static final DeferredItem<Item> EYE_OF_RA;
	static {
		TANK_ROLE = register("tank_role", TankRoleItem::new);
		GIANT_ROLE = register("giant_role", GiantRoleItem::new);
		GUARDIAN_ROLE = register("guardian_role", GuardianRoleItem::new);
		BARBARIAN_ROLE = register("barbarian_role", BarbarianRoleItem::new);
		ASSASSIN_ROLE = register("assassin_role", AssassinRoleItem::new);
		SOLDIER_ROLE = register("soldier_role", SoldierRoleItem::new);
		INVESTIGATOR_ROLE = register("investigator_role", InvestigatorRoleItem::new);
		HUNTER_ROLE = register("hunter_role", HunterRoleItem::new);
		MONK_ROLE = register("monk_role", MonkRoleItem::new);
		WIZARD_ROLE = register("wizard_role", WizardRoleItem::new);
		SUMMONER_ROLE = register("summoner_role", SummonerRoleItem::new);
		DRUID_ROLE = register("druid_role", DruidRoleItem::new);
		STEEL_INGOT = register("steel_ingot", SteelIngotItem::new);
		STEEL_PLATE = register("steel_plate", SteelPlateItem::new);
		TITANIUM_INGOT = register("titanium_ingot", TitaniumIngotItem::new);
		TITANIUM_ORE = block(MythicrealmsModBlocks.TITANIUM_ORE);
		VIBRANIUM_ORE = block(MythicrealmsModBlocks.VIBRANIUM_ORE);
		VIBRANIUM_INGOT = register("vibranium_ingot", VibraniumIngotItem::new);
		STEEL_PICKAXE = register("steel_pickaxe", SteelPickaxeItem::new);
		STEEL_AXE = register("steel_axe", SteelAxeItem::new);
		STEEL_SWORD = register("steel_sword", SteelSwordItem::new);
		STEEL_SHOVEL = register("steel_shovel", SteelShovelItem::new);
		STEEL_HOE = register("steel_hoe", SteelHoeItem::new);
		ADAMANT_ORE = block(MythicrealmsModBlocks.ADAMANT_ORE);
		ADAMANT_INGOT = register("adamant_ingot", AdamantIngotItem::new);
		GHOST_HORSE_SPAWN_EGG = register("ghost_horse_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.GHOST_HORSE.get(), properties));
		NIGHTMARE_HORSE_SPAWN_EGG = register("nightmare_horse_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.NIGHTMARE_HORSE.get(), properties));
		HIPPOCAMPUS_SPAWN_EGG = register("hippocampus_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.HIPPOCAMPUS.get(), properties));
		MINERS_DREAM = register("miners_dream", MinersDreamItem::new);
		CAVE_MAGIC_BOOK = register("cave_magic_book", CaveMagicBookItem::new);
		DASH_MAGIC_BOOK = register("dash_magic_book", DashMagicBookItem::new);
		EARTHQUAKE_MAGIC_BOOK = register("earthquake_magic_book", EarthquakeMagicBookItem::new);
		FIRE_BALL_MAGIC_BOOK = register("fire_ball_magic_book", FireBallMagicBookItem::new);
		GHOST_MODE_MAGIC_BOOK = register("ghost_mode_magic_book", GhostModeMagicBookItem::new);
		HEAL_MAGIC_BOOK = register("heal_magic_book", HealMagicBookItem::new);
		ICE_BALL_MAGIC_BOOK = register("ice_ball_magic_book", IceBallMagicBookItem::new);
		LIFE_STEAL_MAGIC_BOOK = register("life_steal_magic_book", LifeStealMagicBookItem::new);
		METEOR_MAGIC_BOOK = register("meteor_magic_book", MeteorMagicBookItem::new);
		NECROMANCER_MAGIC_BOOK = register("necromancer_magic_book", NecromancerMagicBookItem::new);
		SAND_STORM_MAGIC_BOOK = register("sand_storm_magic_book", SandStormMagicBookItem::new);
		SMOKE_MODE_MAGIC_BOOK = register("smoke_mode_magic_book", SmokeModeMagicBookItem::new);
		SOULFORCE_STEAL_MAGIC_BOOK = register("soulforce_steal_magic_book", SoulforceStealMagicBookItem::new);
		STOP_TIME_MAGIC_BOOK = register("stop_time_magic_book", StopTimeMagicBookItem::new);
		THUNDER_MAGIC_BOOK = register("thunder_magic_book", ThunderMagicBookItem::new);
		HIGHEST_SOUND_MAGIC_BOOK = register("highest_sound_magic_book", HighestSoundMagicBookItem::new);
		ACCELARATION_MAGIC_BOOK = register("accelaration_magic_book", AccelarationMagicBookItem::new);
		EXPELL_MAGIC_BOOK = register("expell_magic_book", ExpellMagicBookItem::new);
		DETECT_MAGIC_BOOK = register("detect_magic_book", DetectMagicBookItem::new);
		VULCAN_MAGIC_BOOK = register("vulcan_magic_book", VulcanMagicBookItem::new);
		BLACK_HOLE_MAGIC_BOOK = register("black_hole_magic_book", BlackHoleMagicBookItem::new);
		REFLECT_MAGIC_BOOK = register("reflect_magic_book", ReflectMagicBookItem::new);
		DEEPWORLD_TRAVEL_MACHINE = block(MythicrealmsModBlocks.DEEPWORLD_TRAVEL_MACHINE, new Item.Properties().stacksTo(1));
		DEEPWORLD_PORTAL = block(MythicrealmsModBlocks.DEEPWORLD_PORTAL, new Item.Properties().rarity(Rarity.EPIC));
		LUNAR_BLOCK = block(MythicrealmsModBlocks.LUNAR_BLOCK);
		POISON_CLOUD_MAGIC_BOOK = register("poison_cloud_magic_book", PoisonCloudMagicBookItem::new);
		LIGHT_TRAVEL_MAGIC_BOOK = register("light_travel_magic_book", LightTravelMagicBookItem::new);
		WATER_BREATH_MAGIC_BOOK = register("water_breath_magic_book", WaterBreathMagicBookItem::new);
		PANDEMIC_SPAWN_EGG = register("pandemic_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.PANDEMIC.get(), properties));
		YETI_SPAWN_EGG = register("yeti_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.YETI.get(), properties));
		JOKER_SPAWN_EGG = register("joker_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.JOKER.get(), properties));
		VAMPIRE_SPAWN_EGG = register("vampire_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.VAMPIRE.get(), properties));
		BLOOD_LOG = block(MythicrealmsModBlocks.BLOOD_LOG);
		BLOOD_WOOD = block(MythicrealmsModBlocks.BLOOD_WOOD);
		STRIPPED_BLOOD_LOG = block(MythicrealmsModBlocks.STRIPPED_BLOOD_LOG);
		STRIPPED_BLOOD_WOOD = block(MythicrealmsModBlocks.STRIPPED_BLOOD_WOOD);
		BLOOD_PLANKS = block(MythicrealmsModBlocks.BLOOD_PLANKS);
		BLOOD_LEAVES = block(MythicrealmsModBlocks.BLOOD_LEAVES);
		BLOOD_STAIRS = block(MythicrealmsModBlocks.BLOOD_STAIRS);
		BLOOD_SLAB = block(MythicrealmsModBlocks.BLOOD_SLAB);
		BLOOD_FENCE = block(MythicrealmsModBlocks.BLOOD_FENCE);
		BLOOD_FENCE_GATE = block(MythicrealmsModBlocks.BLOOD_FENCE_GATE);
		BLOOD_DOOR = doubleBlock(MythicrealmsModBlocks.BLOOD_DOOR);
		BLOOD_TRAPDOOR = block(MythicrealmsModBlocks.BLOOD_TRAPDOOR);
		BLOOD_PRESSURE_PLATE = block(MythicrealmsModBlocks.BLOOD_PRESSURE_PLATE);
		BLOOD_BUTTON = block(MythicrealmsModBlocks.BLOOD_BUTTON);
		BLOOD_SAPLING = block(MythicrealmsModBlocks.BLOOD_SAPLING);
		BLOOD_BOTTLE = register("blood_bottle", BloodBottleItem::new);
		BLOOD_INGOT = register("blood_ingot", BloodIngotItem::new);
		DRACULA_SPAWN_EGG = register("dracula_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.DRACULA.get(), properties));
		BLOOD_POTIONS = register("blood_potions", BloodPotionsItem::new);
		LAVA_GOLEM_SPAWN_EGG = register("lava_golem_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.LAVA_GOLEM.get(), properties));
		BLOOD_ARMOR_HELMET = register("blood_armor_helmet", BloodArmorItem.Helmet::new);
		BLOOD_ARMOR_CHESTPLATE = register("blood_armor_chestplate", BloodArmorItem.Chestplate::new);
		BLOOD_ARMOR_LEGGINGS = register("blood_armor_leggings", BloodArmorItem.Leggings::new);
		BLOOD_ARMOR_BOOTS = register("blood_armor_boots", BloodArmorItem.Boots::new);
		NOBLE_STEEL = register("noble_steel", NobleSteelItem::new);
		SAMURAI_ARMOR_HELMET = register("samurai_armor_helmet", SamuraiArmorItem.Helmet::new);
		SAMURAI_ARMOR_CHESTPLATE = register("samurai_armor_chestplate", SamuraiArmorItem.Chestplate::new);
		SAMURAI_ARMOR_LEGGINGS = register("samurai_armor_leggings", SamuraiArmorItem.Leggings::new);
		SAMURAI_ARMOR_BOOTS = register("samurai_armor_boots", SamuraiArmorItem.Boots::new);
		GHOST_MUSHROOM = block(MythicrealmsModBlocks.GHOST_MUSHROOM, new Item.Properties().fireResistant());
		BLOOD_GRASS = block(MythicrealmsModBlocks.BLOOD_GRASS);
		MUMMY_SPAWN_EGG = register("mummy_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.MUMMY.get(), properties));
		PHARAOH_SPAWN_EGG = register("pharaoh_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.PHARAOH.get(), properties));
		ENT_SPAWN_EGG = register("ent_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.ENT.get(), properties));
		KITSUNE_SPAWN_EGG = register("kitsune_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.KITSUNE.get(), properties));
		STURGEON_SPAWN_EGG = register("sturgeon_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.STURGEON.get(), properties));
		VENRAID_SPAWN_EGG = register("venraid_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.VENRAID.get(), properties));
		VENRAID_SCALE = register("venraid_scale", VenraidScaleItem::new);
		VENRAID_ARMOR_HELMET = register("venraid_armor_helmet", VenraidArmorItem.Helmet::new);
		VENRAID_ARMOR_CHESTPLATE = register("venraid_armor_chestplate", VenraidArmorItem.Chestplate::new);
		VENRAID_ARMOR_LEGGINGS = register("venraid_armor_leggings", VenraidArmorItem.Leggings::new);
		VENRAID_ARMOR_BOOTS = register("venraid_armor_boots", VenraidArmorItem.Boots::new);
		BANDAGE = register("bandage", BandageItem::new);
		PHARAOH_ARMOR_HELMET = register("pharaoh_armor_helmet", PharaohArmorItem.Helmet::new);
		PHARAOH_ARMOR_CHESTPLATE = register("pharaoh_armor_chestplate", PharaohArmorItem.Chestplate::new);
		PHARAOH_ARMOR_LEGGINGS = register("pharaoh_armor_leggings", PharaohArmorItem.Leggings::new);
		PHARAOH_ARMOR_BOOTS = register("pharaoh_armor_boots", PharaohArmorItem.Boots::new);
		SCARAB_GEM = register("scarab_gem", ScarabGemItem::new);
		TECH_ARMOR_HELMET = register("tech_armor_helmet", TechArmorItem.Helmet::new);
		TECH_ARMOR_CHESTPLATE = register("tech_armor_chestplate", TechArmorItem.Chestplate::new);
		TECH_ARMOR_LEGGINGS = register("tech_armor_leggings", TechArmorItem.Leggings::new);
		TECH_ARMOR_BOOTS = register("tech_armor_boots", TechArmorItem.Boots::new);
		NINJA_ARMOR_HELMET = register("ninja_armor_helmet", NinjaArmorItem.Helmet::new);
		NINJA_ARMOR_CHESTPLATE = register("ninja_armor_chestplate", NinjaArmorItem.Chestplate::new);
		NINJA_ARMOR_LEGGINGS = register("ninja_armor_leggings", NinjaArmorItem.Leggings::new);
		NINJA_ARMOR_BOOTS = register("ninja_armor_boots", NinjaArmorItem.Boots::new);
		REINFORCED_LEATHER = register("reinforced_leather", ReinforcedLeatherItem::new);
		ANGEL_FEATHER = register("angel_feather", AngelFeatherItem::new);
		ANGEL_INGOT = register("angel_ingot", AngelIngotItem::new);
		ANGEL_ARMOR_HELMET = register("angel_armor_helmet", AngelArmorItem.Helmet::new);
		ANGEL_ARMOR_CHESTPLATE = register("angel_armor_chestplate", AngelArmorItem.Chestplate::new);
		ANGEL_ARMOR_LEGGINGS = register("angel_armor_leggings", AngelArmorItem.Leggings::new);
		ANGEL_ARMOR_BOOTS = register("angel_armor_boots", AngelArmorItem.Boots::new);
		DEMON_ARMOR_HELMET = register("demon_armor_helmet", DemonArmorItem.Helmet::new);
		DEMON_ARMOR_CHESTPLATE = register("demon_armor_chestplate", DemonArmorItem.Chestplate::new);
		DEMON_ARMOR_LEGGINGS = register("demon_armor_leggings", DemonArmorItem.Leggings::new);
		DEMON_ARMOR_BOOTS = register("demon_armor_boots", DemonArmorItem.Boots::new);
		DEMON_SCALE = register("demon_scale", DemonScaleItem::new);
		DEMON_INGOT = register("demon_ingot", DemonIngotItem::new);
		ENT_ARMOR_HELMET = register("ent_armor_helmet", EntArmorItem.Helmet::new);
		ENT_ARMOR_CHESTPLATE = register("ent_armor_chestplate", EntArmorItem.Chestplate::new);
		ENT_ARMOR_LEGGINGS = register("ent_armor_leggings", EntArmorItem.Leggings::new);
		ENT_ARMOR_BOOTS = register("ent_armor_boots", EntArmorItem.Boots::new);
		MAGIC_SAPLING = block(MythicrealmsModBlocks.MAGIC_SAPLING);
		MAGIC_LOG = block(MythicrealmsModBlocks.MAGIC_LOG);
		MAGIC_WOOD = block(MythicrealmsModBlocks.MAGIC_WOOD);
		STRIPPED_MAGIC_LOG = block(MythicrealmsModBlocks.STRIPPED_MAGIC_LOG);
		STRIPPED_MAGIC_WOOD = block(MythicrealmsModBlocks.STRIPPED_MAGIC_WOOD);
		MAGIC_PLANKS = block(MythicrealmsModBlocks.MAGIC_PLANKS);
		MAGIC_LEAVES = block(MythicrealmsModBlocks.MAGIC_LEAVES);
		MAGIC_STAIRS = block(MythicrealmsModBlocks.MAGIC_STAIRS);
		MAGIC_SLAB = block(MythicrealmsModBlocks.MAGIC_SLAB);
		MAGIC_FENCE = block(MythicrealmsModBlocks.MAGIC_FENCE);
		MAGIC_FENCE_GATE = block(MythicrealmsModBlocks.MAGIC_FENCE_GATE);
		MAGIC_DOOR = doubleBlock(MythicrealmsModBlocks.MAGIC_DOOR);
		MAGIC_TRAPDOOR = block(MythicrealmsModBlocks.MAGIC_TRAPDOOR);
		MAGIC_PRESSURE_PLATE = block(MythicrealmsModBlocks.MAGIC_PRESSURE_PLATE);
		MAGIC_BUTTON = block(MythicrealmsModBlocks.MAGIC_BUTTON);
		TEMPEST_MAGIC_BOOK = register("tempest_magic_book", TempestMagicBookItem::new);
		BARRIER_MAGIC_BOOK = register("barrier_magic_book", BarrierMagicBookItem::new);
		BLOOD_SWORD = register("blood_sword", BloodSwordItem::new);
		BACKPACK_ITEM = register("backpack_item", BackpackItemItem::new);
		SHIELD_OF_ATHENA = register("shield_of_athena", ShieldOfAthenaItem::new);
		BOW_OF_APOLLO = register("bow_of_apollo", BowOfApolloItem::new);
		PUMPKIN_STAFF = register("pumpkin_staff", PumpkinStaffItem::new);
		VENRAID_SWORD = register("venraid_sword", VenraidSwordItem::new);
		NECRO_BOOK = register("necro_book", NecroBookItem::new);
		RELIGION_BOOK = register("religion_book", ReligionBookItem::new);
		SOULFORCE_BOOK = register("soulforce_book", SoulforceBookItem::new);
		ILLUMINATY_ITEM = register("illuminaty_item", IlluminatyItemItem::new);
		TANMAKU_SWORD = register("tanmaku_sword", TanmakuSwordItem::new);
		EGYPTIAN_SWORD = register("egyptian_sword", EgyptianSwordItem::new);
		TANMAKE = register("tanmake", TanmakeItem::new);
		MAGNET = register("magnet", MagnetItem::new);
		MAGNETIC_ROCK = block(MythicrealmsModBlocks.MAGNETIC_ROCK);
		ANTI_MAGNETIC_ROCK = block(MythicrealmsModBlocks.ANTI_MAGNETIC_ROCK);
		MAGNET_ARMOR_HELMET = register("magnet_armor_helmet", MagnetArmorItem.Helmet::new);
		MAGNET_ARMOR_CHESTPLATE = register("magnet_armor_chestplate", MagnetArmorItem.Chestplate::new);
		MAGNET_ARMOR_LEGGINGS = register("magnet_armor_leggings", MagnetArmorItem.Leggings::new);
		MAGNET_ARMOR_BOOTS = register("magnet_armor_boots", MagnetArmorItem.Boots::new);
		PALLADIO_BLOCK = block(MythicrealmsModBlocks.PALLADIO_BLOCK);
		PALLADIO_INGOT = register("palladio_ingot", PalladioIngotItem::new);
		RAW_PALLADIO = register("raw_palladio", RawPalladioItem::new);
		RAW_ADAMANT = register("raw_adamant", RawAdamantItem::new);
		RAW_TITANIUM = register("raw_titanium", RawTitaniumItem::new);
		RAW_VIBRANIUM = register("raw_vibranium", RawVibraniumItem::new);
		MANA_POTION = register("mana_potion", ManaPotionItem::new);
		MANA_BOTTLE = register("mana_bottle", ManaBottleItem::new);
		ANGEL_SPAWN_EGG = register("angel_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.ANGEL.get(), properties));
		DEMON_SPAWN_EGG = register("demon_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.DEMON.get(), properties));
		YGGDRASIL_LOG = block(MythicrealmsModBlocks.YGGDRASIL_LOG);
		YGGDRASIL_WOOD = block(MythicrealmsModBlocks.YGGDRASIL_WOOD);
		STRIPPED_YGGDRASIL_LOG = block(MythicrealmsModBlocks.STRIPPED_YGGDRASIL_LOG);
		STRIPPED_YGGDRASIL_WOOD = block(MythicrealmsModBlocks.STRIPPED_YGGDRASIL_WOOD);
		YGGDRASIL_PLANKS = block(MythicrealmsModBlocks.YGGDRASIL_PLANKS);
		YGGDRASIL_LEAVES = block(MythicrealmsModBlocks.YGGDRASIL_LEAVES);
		YGGDRASIL_STAIRS = block(MythicrealmsModBlocks.YGGDRASIL_STAIRS);
		YGGDRASIL_SLAB = block(MythicrealmsModBlocks.YGGDRASIL_SLAB);
		YGGDRASIL_FENCE = block(MythicrealmsModBlocks.YGGDRASIL_FENCE);
		YGGDRASIL_FENCE_GATE = block(MythicrealmsModBlocks.YGGDRASIL_FENCE_GATE);
		YGGDRASIL_DOOR = doubleBlock(MythicrealmsModBlocks.YGGDRASIL_DOOR);
		YGGDRASIL_TRAPDOOR = block(MythicrealmsModBlocks.YGGDRASIL_TRAPDOOR);
		YGGDRASIL_PRESSURE_PLATE = block(MythicrealmsModBlocks.YGGDRASIL_PRESSURE_PLATE);
		YGGDRASIL_BUTTON = block(MythicrealmsModBlocks.YGGDRASIL_BUTTON);
		YGGDRASIL_SAPLING = block(MythicrealmsModBlocks.YGGDRASIL_SAPLING);
		WENDIGO_SPAWN_EGG = register("wendigo_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.WENDIGO.get(), properties));
		TECH_GOOGLES_ITEM = register("tech_googles_item", TechGooglesItemItem::new);
		PALLADIO_ARMOR_HELMET = register("palladio_armor_helmet", PalladioArmorItem.Helmet::new);
		PALLADIO_ARMOR_CHESTPLATE = register("palladio_armor_chestplate", PalladioArmorItem.Chestplate::new);
		PALLADIO_ARMOR_LEGGINGS = register("palladio_armor_leggings", PalladioArmorItem.Leggings::new);
		PALLADIO_ARMOR_BOOTS = register("palladio_armor_boots", PalladioArmorItem.Boots::new);
		URANIUM = register("uranium", UraniumItem::new);
		URANIUM_BLOCK = block(MythicrealmsModBlocks.URANIUM_BLOCK);
		ENRICHED_URANIUM = register("enriched_uranium", EnrichedUraniumItem::new);
		XOCHITL_POWDER = register("xochitl_powder", XochitlPowderItem::new);
		XOCHITL_LEATHER = register("xochitl_leather", XochitlLeatherItem::new);
		XOCHITL_INGOT = register("xochitl_ingot", XochitlIngotItem::new);
		XOCHITL_SPAWN_EGG = register("xochitl_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.XOCHITL.get(), properties));
		STAR_DUST = register("star_dust", StarDustItem::new);
		SAND_OF_STAR = block(MythicrealmsModBlocks.SAND_OF_STAR);
		TOXIC_SAND = block(MythicrealmsModBlocks.TOXIC_SAND);
		MYTHRILL = register("mythrill", MythrillItem::new);
		SKIES_STONE = block(MythicrealmsModBlocks.SKIES_STONE);
		MYTHRILL_ORE = block(MythicrealmsModBlocks.MYTHRILL_ORE);
		SKIES_GRASS = block(MythicrealmsModBlocks.SKIES_GRASS);
		SKIES_STONE_BRICKS = block(MythicrealmsModBlocks.SKIES_STONE_BRICKS);
		TOXIC_SLIME = register("toxic_slime", ToxicSlimeItem::new);
		ULTIMATE_INGOT = register("ultimate_ingot", UltimateIngotItem::new);
		NANOS = register("nanos", NanosItem::new);
		PEDESTAL = block(MythicrealmsModBlocks.PEDESTAL);
		LUNAR_COBBLESTONE = block(MythicrealmsModBlocks.LUNAR_COBBLESTONE);
		LUNAR_COBBLE_SLAB = block(MythicrealmsModBlocks.LUNAR_COBBLE_SLAB);
		NANO_ARMOR_HELMET = register("nano_armor_helmet", NanoArmorItem.Helmet::new);
		NANO_ARMOR_CHESTPLATE = register("nano_armor_chestplate", NanoArmorItem.Chestplate::new);
		NANO_ARMOR_LEGGINGS = register("nano_armor_leggings", NanoArmorItem.Leggings::new);
		NANO_ARMOR_BOOTS = register("nano_armor_boots", NanoArmorItem.Boots::new);
		ACTIVED_NANO = register("actived_nano", ActivedNanoItem::new);
		CRYSTAL_BARRIER_BLOCK = block(MythicrealmsModBlocks.CRYSTAL_BARRIER_BLOCK, new Item.Properties().fireResistant());
		GLACITE = register("glacite", GlaciteItem::new);
		GLACITE_ORE = block(MythicrealmsModBlocks.GLACITE_ORE);
		FLAMITE_ORE = block(MythicrealmsModBlocks.FLAMITE_ORE);
		FLAMITE = register("flamite", FlamiteItem::new);
		NANITE = register("nanite", NaniteItem::new);
		XOCHITL_ARMOR_HELMET = register("xochitl_armor_helmet", XochitlArmorItem.Helmet::new);
		XOCHITL_ARMOR_CHESTPLATE = register("xochitl_armor_chestplate", XochitlArmorItem.Chestplate::new);
		XOCHITL_ARMOR_LEGGINGS = register("xochitl_armor_leggings", XochitlArmorItem.Leggings::new);
		XOCHITL_ARMOR_BOOTS = register("xochitl_armor_boots", XochitlArmorItem.Boots::new);
		WENDIGO_BONE = register("wendigo_bone", WendigoBoneItem::new);
		WENDIGO_ARMOR_ARMOR_HELMET = register("wendigo_armor_armor_helmet", WendigoArmorArmorItem.Helmet::new);
		WENDIGO_ARMOR_ARMOR_CHESTPLATE = register("wendigo_armor_armor_chestplate", WendigoArmorArmorItem.Chestplate::new);
		WENDIGO_ARMOR_ARMOR_LEGGINGS = register("wendigo_armor_armor_leggings", WendigoArmorArmorItem.Leggings::new);
		WENDIGO_ARMOR_ARMOR_BOOTS = register("wendigo_armor_armor_boots", WendigoArmorArmorItem.Boots::new);
		ORICALC = register("oricalc", OricalcItem::new);
		MAGIC_ARMOR_HELMET = register("magic_armor_helmet", MagicArmorItem.Helmet::new);
		MAGIC_ARMOR_CHESTPLATE = register("magic_armor_chestplate", MagicArmorItem.Chestplate::new);
		MAGIC_ARMOR_LEGGINGS = register("magic_armor_leggings", MagicArmorItem.Leggings::new);
		MAGIC_ARMOR_BOOTS = register("magic_armor_boots", MagicArmorItem.Boots::new);
		MAGIC_ARMOR_MAGIC_BOOK = register("magic_armor_magic_book", MagicArmorMagicBookItem::new);
		SUBSTITUTE_MAGIC_BOOK = register("substitute_magic_book", SubstituteMagicBookItem::new);
		FIRE_WAVE_MAGIC_BOOK = register("fire_wave_magic_book", FireWaveMagicBookItem::new);
		FLY_MAGIC_BOOK = register("fly_magic_book", FlyMagicBookItem::new);
		LANCE = register("lance", LanceItem::new);
		CHIMERA_GUN_ITEM = register("chimera_gun_item", ChimeraGunItemItem::new);
		SPECTATE_MAGIC_BOOK = register("spectate_magic_book", SpectateMagicBookItem::new);
		TECH_JETPACK_ITEM = register("tech_jetpack_item", TechJetpackItemItem::new);
		TOMOE_RING_ITEM = register("tomoe_ring_item", TomoeRingItemItem::new);
		UNICORN_SPAWN_EGG = register("unicorn_spawn_egg", properties -> new SpawnEggItem(MythicrealmsModEntities.UNICORN.get(), properties));
		RING = register("ring", RingItem::new);
		WATER_STONE = block(MythicrealmsModBlocks.WATER_STONE);
		OCEAN_PORTAL = block(MythicrealmsModBlocks.OCEAN_PORTAL, new Item.Properties().rarity(Rarity.EPIC));
		ICE_AGE_MAGIC_BOOK = register("ice_age_magic_book", IceAgeMagicBookItem::new);
		DESERT_MAGIC_BOOK = register("desert_magic_book", DesertMagicBookItem::new);
		FANG = register("fang", FangItem::new);
		WEREWOLF_FANG = register("werewolf_fang", WerewolfFangItem::new);
		WEREWOLF_ARMOR_HELMET = register("werewolf_armor_helmet", WerewolfArmorItem.Helmet::new);
		WEREWOLF_ARMOR_CHESTPLATE = register("werewolf_armor_chestplate", WerewolfArmorItem.Chestplate::new);
		WEREWOLF_ARMOR_LEGGINGS = register("werewolf_armor_leggings", WerewolfArmorItem.Leggings::new);
		WEREWOLF_ARMOR_BOOTS = register("werewolf_armor_boots", WerewolfArmorItem.Boots::new);
		BLOOD_CRYSTAL = register("blood_crystal", BloodCrystalItem::new);
		WEREWOLF_CHESTPLATE_INCOMPLETE = register("werewolf_chestplate_incomplete", WerewolfChestplateIncompleteItem::new);
		CRYSTAL = register("crystal", CrystalItem::new);
		CRYSTAL_ORE = block(MythicrealmsModBlocks.CRYSTAL_ORE);
		SKY_PORTAL = block(MythicrealmsModBlocks.SKY_PORTAL, new Item.Properties().rarity(Rarity.EPIC));
		SOLID_BLOOD = block(MythicrealmsModBlocks.SOLID_BLOOD);
		BLOOD_BUCKET = register("blood_bucket", BloodItem::new);
		CAPACITOR = register("capacitor", CapacitorItem::new);
		TESLA_ARMOR_HELMET = register("tesla_armor_helmet", TeslaArmorItem.Helmet::new);
		TESLA_ARMOR_CHESTPLATE = register("tesla_armor_chestplate", TeslaArmorItem.Chestplate::new);
		TESLA_ARMOR_LEGGINGS = register("tesla_armor_leggings", TeslaArmorItem.Leggings::new);
		TESLA_ARMOR_BOOTS = register("tesla_armor_boots", TeslaArmorItem.Boots::new);
		DIVINE_SWORD = register("divine_sword", DivineSwordItem::new);
		MJOLNIR = register("mjolnir", MjolnirItem::new);
		HAMMER = register("hammer", HammerItem::new);
		TANMAKU_HAMMER = register("tanmaku_hammer", TanmakuHammerItem::new);
		KATANA = register("katana", KatanaItem::new);
		PRE_HISTORY_ARMOR_HELMET = register("pre_history_armor_helmet", PreHistoryArmorItem.Helmet::new);
		PRE_HISTORY_ARMOR_CHESTPLATE = register("pre_history_armor_chestplate", PreHistoryArmorItem.Chestplate::new);
		PRE_HISTORY_ARMOR_LEGGINGS = register("pre_history_armor_leggings", PreHistoryArmorItem.Leggings::new);
		PRE_HISTORY_ARMOR_BOOTS = register("pre_history_armor_boots", PreHistoryArmorItem.Boots::new);
		SOUL_ITEM = register("soul_item", SoulItemItem::new);
		SOULFORCE_POTION = register("soulforce_potion", SoulforcePotionItem::new);
		SOUL_INGOT = register("soul_ingot", SoulIngotItem::new);
		EGYPTIAN_GOD_ARMOR_HELMET = register("egyptian_god_armor_helmet", EgyptianGodArmorItem.Helmet::new);
		EGYPTIAN_GOD_ARMOR_CHESTPLATE = register("egyptian_god_armor_chestplate", EgyptianGodArmorItem.Chestplate::new);
		EGYPTIAN_GOD_ARMOR_LEGGINGS = register("egyptian_god_armor_leggings", EgyptianGodArmorItem.Leggings::new);
		EGYPTIAN_GOD_ARMOR_BOOTS = register("egyptian_god_armor_boots", EgyptianGodArmorItem.Boots::new);
		DIVINE_INGOT = register("divine_ingot", DivineIngotItem::new);
		EYE_OF_RA = register("eye_of_ra", EyeOfRaItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new DoubleHighBlockItem(block.get(), prop), properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new BackpackItemInventoryCapability(stack), BACKPACK_ITEM.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), BLOOD_BUCKET.get());
	}
}