modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="mythicrealms"
version="0.0.5"
displayName="MythicRealms"
displayURL="https://sites.google.com/view/carsantos7/mythic-realms"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="CarSantos7"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "mythicrealms.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.mythicrealms]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mythicrealms]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.mythicrealms]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration